const TABLET_BREAKPOINT_PX = 768;
const MOBILE_IMAGE_WIDTH_PX = 150;
const DESKTOP_IMAGE_WIDTH_VW = 33;

export const IMAGE_SIZES = `(min-width: ${TABLET_BREAKPOINT_PX}px) ${DESKTOP_IMAGE_WIDTH_VW}vw, ${MOBILE_IMAGE_WIDTH_PX}px`;
